name: Build App & Push to container registry

jobs:
  build-and-push-package:
    runs-on: ubuntu-latest
    env: 
      working-directory: .
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
         registry: ghcr.io
         username: ${{ github.actor }};
         password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.7.0
      with:
        push: true
        context: ${{env.working-directory}}
        tags: |
          ghcr.io/bjork-dev/todoapp:latest
          ghcr.io/bjork-dev/todoapp:${{ github.run_number }}
